# Generated by Django 4.2.13 on 2024-05-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='telegram_link',
            field=models.CharField(max_length=70, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.TextField(verbose_name='Полное имя'),
        ),
    ]
