# Generated by Django 4.2.13 on 2024-05-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_link_telegram_link_alter_worker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_tg_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='Telegram ID'),
        ),
    ]
