# Generated by Django 5.0.6 on 2024-05-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sale percent'),
        ),
    ]
