# Generated by Django 5.1 on 2024-08-21 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBallance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(unique=True, verbose_name='ID пользователя')),
                ('ballance', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Балланс руб.')),
            ],
            options={
                'verbose_name': 'Баланс пользователя',
                'verbose_name_plural': 'Балансы пользователей',
            },
        ),
        migrations.CreateModel(
            name='BallanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Списание/пополнение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('service', models.CharField(max_length=128, verbose_name='Сервис пополнения/списания')),
                ('description', models.TextField(verbose_name='Описание транзакции')),
                ('user_ballance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballance.userballance', verbose_name='Баланс Пользователя')),
            ],
        ),
    ]
