# Generated by Django 5.1.1 on 2024-09-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Длина')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, choices=[('1A', '1А'), ('1B', '1Б'), ('2A', '2А'), ('2B', '2Б'), ('3A', '3А'), ('3B', '3Б')], null=True, verbose_name='Зимой')),
                ('summer', models.CharField(blank=True, choices=[('1A', '1А'), ('1B', '1Б'), ('2A', '2А'), ('2B', '2Б'), ('3A', '3А'), ('3B', '3Б')], null=True, verbose_name='Летом')),
                ('autumn', models.CharField(blank=True, choices=[('1A', '1А'), ('1B', '1Б'), ('2A', '2А'), ('2B', '2Б'), ('3A', '3А'), ('3B', '3Б')], null=True, verbose_name='Осенью')),
                ('spring', models.CharField(blank=True, choices=[('1A', '1А'), ('1B', '1Б'), ('2A', '2А'), ('2B', '2Б'), ('3A', '3А'), ('3B', '3Б')], null=True, verbose_name='Весной')),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('beautyTitle', models.CharField(verbose_name='Загаловок')),
                ('title', models.CharField(verbose_name='Название')),
                ('other_titles', models.CharField(verbose_name='Доп. название')),
                ('connect', models.CharField()),
                ('add_time', models.DateTimeField(verbose_name='Дата добавления пользователем')),
                ('status', models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='new', verbose_name='Статус модерации')),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='perevals.coordinates', verbose_name='Координаты перевала')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Добавлено пользователем')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='perevals.perevallevel', verbose_name='Уровень сложности')),
            ],
            options={
                'db_table': 'pereval_added',
            },
        ),
        migrations.CreateModel(
            name='PerevalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Описание к фотографии')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('to_pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevals.pereval', verbose_name='Фото к перевалу')),
            ],
        ),
    ]
