services:

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env


  web:
    build: 
      context: ./app
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/static
    env_file:
      - ./.env


  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/



volumes:
  postgres_data:
  static_value:
