# Generated by Django 5.1.1 on 2024-09-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Эл. почта')),
                ('fam', models.CharField(verbose_name='Фамилия пользователя')),
                ('name', models.CharField(verbose_name='Имя пользователя')),
                ('oct', models.CharField(verbose_name='Отчество пользователя')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
            ],
        ),
    ]
