# Generated by Django 5.1.2 on 2024-10-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=10, unique=True, verbose_name='Путь редиректа')),
                ('redirect_to', models.URLField(verbose_name='Редирект на')),
            ],
        ),
    ]
