services:

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - api_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env


  web:
    build: 
      context: ./app
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - api_static_value:/static
      - api_media_data:/media
    env_file:
      - ./.env


  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - api_static_value:/var/html/static/
      - api_media_data:/var/html/media/



volumes:
  api_postgres_data:
  api_static_value:
  api_media_data:
